CREATE TABLE FILES (
ID NUMBER,
CONSTRAINT ID_FILE_PK PRIMARY KEY (ID),
FILE_NAME NVARCHAR2 (128),
FILE_FORMAT NVARCHAR2 (10),
FILE_SIZE NUMBER (9,2),
STORAGE_ID NUMBER,
CONSTRAINT FILE_STORAGE_ID_FK FOREIGN KEY (STORAGE_ID) REFERENCES STORAGE(ID)
);

CREATE SEQUENCE SQ_AUTOINC_FILE
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;


CREATE OR REPLACE TRIGGER AUTOINCR_TRG_FILE
  BEFORE INSERT ON FILES
  FOR EACH ROW
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SQ_AUTOINC_FILE.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;


-- ИСПОЛЬЗОВАНИЕ INSERT
INSERT INTO STORAGE (ID, STORAGE_COUNTRY, STORAGE_MAX_SIZE, FILE_FORMAT) VALUES (SQ_AUTOINC_STORAGE.NEXTVAL, 'USA', 1000, 'TXT, JPG');