CREATE TABLE STORAGE (
ID NUMERIC,
CONSTRAINT ID_STORAGE_PK PRIMARY KEY (ID),
STORAGE_COUNTRY NVARCHAR2 (128),
STORAGE_MAX_SIZE NUMERIC (19,0),
FILE_FORMAT NVARCHAR2 (128)
);

CREATE SEQUENCE SQ_AUTOINC_STORAGE
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;


CREATE OR REPLACE TRIGGER AUTOINCR_TRG_STORAGE
  BEFORE INSERT ON STORAGE
  FOR EACH ROW
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT SQ_AUTOINC_STORAGE.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;


-- ИСПОЛЬЗОВАНИЕ INSERT
INSERT INTO STORAGE (ID, STORAGE_COUNTRY, STORAGE_MAX_SIZE, FILE_FORMAT) VALUES (SQ_AUTOINC_STORAGE.NEXTVAL, 'USA', 1000, 'TXT, JPG');