INSERT INTO STORAGE(STORAGE_COUNTRY, STORAGE_MAX_SIZE, FILE_FORMAT)
VALUES ('UKRAINE', 10000, 'TXT,JPG');

INSERT INTO FILES (FILE_NAME, FILE_FORMAT, FILE_SIZE, STORAGE_ID)
VALUES ('FILE1', 'TXT', 100, 2);

INSERT INTO FILES (FILE_NAME, FILE_FORMAT, FILE_SIZE, STORAGE_ID)
VALUES ('FILE2', 'TXT', 100, 2);

INSERT INTO FILES (FILE_NAME, FILE_FORMAT, FILE_SIZE, STORAGE_ID)
VALUES ('FILE3', 'jpg', 100, 2);

INSERT INTO FILES (FILE_NAME, FILE_FORMAT, FILE_SIZE, STORAGE_ID)
VALUES ('FILE4', 'jpg', 100, 2);


INSERT INTO STORAGE(STORAGE_COUNTRY, STORAGE_MAX_SIZE, FILE_FORMAT)
VALUES ('UKRAINE', 10000, 'JPG');