CREATE TABLE ROOM (
ID NUMBER,
CONSTRAINT ROOM_PK PRIMARY KEY (ID),
NUMBER_OF_GUESTS NUMBER(2,0),
PRICE NUMBER(9,2),
BREAKFAST_INCLUDED NUMBER(1,0) CHECK (BREAKFAST_INCLUDED = 0 OR BREAKFAST_INCLUDED = 1),
PETS_ALLOWED NUMBER(1,0) CHECK (PETS_ALLOWED = 0 OR PETS_ALLOWED = 1),
DATE_AVAILABLE_FROM DATE,
HOTEL_ID NUMBER,
CONSTRAINT HOTEL_ID_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL (ID)
);