CREATE TABLE HOTEL (
ID NUMBER,
CONSTRAINT HOTEL_PK PRIMARY KEY (ID),
NAME NVARCHAR2(255) NOT NULL,
COUNTRY NVARCHAR2(128) NOT NULL,
CITY NVARCHAR2(128) NOT NULL,
STREET NVARCHAR2(128) NOT NULL
);

drop table ROOM;
drop table HOTEL;